Repository dotnet/AspNetCore.Docs.ja-jp, pull requests merged in 2018-06, with the labels that each got.

#38 Update bootstrap.md
  aspnetcore/client-side/bootstrap.md
Labels: Accepted, Linguistic Suggestion

#39 Update bootstrap.md
  aspnetcore/client-side/bootstrap.md
Labels: Accepted, Linguistic Suggestion

#42 スニペットが表示されていないバグを修正
  aspnetcore/includes/RP/da2.md
Labels: Accepted, Source Issue

#40 typoの修正
  aspnetcore/includes/RP/da2.md
Labels: In Progress, Linguistic Suggestion

#55 Masaha03 patch 18
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#53 誤訳の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: In Progress, Linguistic Suggestion

#52 表現の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#51 誤訳の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Linguistic Suggestion, Rejected

#50 表現の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Linguistic Suggestion, Rejected

#49 訳文の品質の向上
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#48 訳の品質の向上
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#47 誤訳の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#46 表現の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#45 誤訳の修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#44 typoの修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion

#43 不明瞭な表現を修正
  aspnetcore/tutorials/razor-pages/validation.md
Labels: Accepted, Linguistic Suggestion
