Repository dotnet/AspNetCore.Docs.ja-jp, pull requests merged in 2020-05, with the labels that each got.

#296 [LOC]Back-Translation "コンソール"→"Console"
  aspnetcore/fundamentals/logging/index.md
Labels: Accepted, Linguistic Suggestion

#298 Update "AspNetCore.Docs.ja-jp/aspnetcore/toc.yml"
  aspnetcore/toc.yml
Labels: Accepted, Linguistic Suggestion, P1

#297 [LOC]Fixed inappropriate japanese "[ パラメーターを受け取る、]"
  aspnetcore/fundamentals/change-tokens.md
Labels: Accepted, Linguistic Suggestion, P1

#299 [LOC]Back-Translation "**Required assets to build and debug are missing from 'MvcMovie'. Add them?**"
  aspnetcore/tutorials/first-mvc-app/start-mvc.md
Labels: Accepted, P1

#300 [LOC]Back-Translation "資産"→"アセット"
  aspnetcore/tutorials/first-mvc-app/start-mvc.md
Labels: Accepted, Linguistic Suggestion, P1

#301 fixed typo
  aspnetcore/fundamentals/configuration/options.md
Labels: Accepted, Linguistic Suggestion, P1

#304 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/fundamentals/static-files.md
Labels: Accepted, Linguistic Suggestion, P1

#302 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/directory-structure.md
Labels: Accepted, Linguistic Suggestion, P1

#306 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/iis/index.md
Labels: Accepted, Linguistic Suggestion, P1

#305 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
Labels: Accepted, Linguistic Suggestion, P1

#311 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  aspnetcore/tutorials/grpc/grpc-start.md
Labels: Accepted, Linguistic Suggestion, P1

#310 [LOC]Fixed inappropriate japanese "[端末]"→"[ターミナル]"
  aspnetcore/tutorials/signalr.md
Labels: Accepted, Linguistic Suggestion, P1

#303 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/client-side/bundling-and-minification.md
Labels: Accepted, Linguistic Suggestion, P1

#308 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/blazor/hosting-models.md
Labels: Accepted, Linguistic Suggestion, P1

#309 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/grpc/dotnet-grpc.md
Labels: Accepted, Linguistic Suggestion, P1

#314 [LOC]Fixed inappropriate japanese "端末"→"ターミナル"
  aspnetcore/data/ef-rp/concurrency.md
Labels: Accepted, Linguistic Suggestion, P1
