Repository dotnet/AspNetCore.Docs.ja-jp, pull requests merged in 2020-06, with the labels that each got.

#325 [LOC]Back-Translation "**ビルドとデバッグに必要な資産が 'MvcMovie' にありません。追加しますか?** "
  aspnetcore/tutorials/first-mvc-app/start-mvc.md
Labels: Accepted, Linguistic Suggestion, P1

#324 [LOC]Back-Translation "資産"→"アセット"
  aspnetcore/fundamentals/metapackage-app.md
Labels: Accepted, Linguistic Suggestion, P1

#326 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/linux-apache.md
Labels: Accepted, Linguistic Suggestion, P1

#327 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/tutorials/first-web-api.md
Labels: Accepted, Linguistic Suggestion, P1

#329 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/windows-service.md
Labels: Accepted, Linguistic Suggestion, P1

#334 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/release-notes/aspnetcore-2.0.md
Labels: Accepted, Linguistic Suggestion, P1

#332 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/fundamentals/host/web-host.md
Labels: Accepted, Linguistic Suggestion, P1

#331 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/includes/signalr-typescript-webpack/npm-run-release.md
Labels: Accepted, Linguistic Suggestion, P1

#330 Fix missing code snippet in Startup.Configure
  aspnetcore/tutorials/signalr-blazor-webassembly.md
Labels: Accepted, Linguistic Suggestion, P1

#335 [LOC]Back-Translation "ビルドとデバッグに必要な～"→"Required assets to build and d…
  aspnetcore/tutorials/razor-pages/razor-pages-start.md
Labels: Accepted, P1

#336 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/index.md
Labels: Accepted, Linguistic Suggestion, P1

#337 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/linux-nginx.md
Labels: Accepted, Linguistic Suggestion, P1

#340 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/client-side/spa-services.md
Labels: Accepted, P1

#339 [LOC]Back-Translation "ビルドとデバッグに必要～"→"Required assets to build and d…
  aspnetcore/tutorials/first-mongo-app.md
Labels: Accepted, In Progress, Linguistic Suggestion, P1

#323 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/blazor/components.md
Labels: Accepted, Linguistic Suggestion, P1

#322 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/fundamentals/url-rewriting.md
Labels: Accepted, Linguistic Suggestion, P1

#338 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/azure/devops/cicd.md
Labels: Accepted, Linguistic Suggestion, P1, Technical Issue

#318 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/iis/index.md
Labels: Accepted, Linguistic Suggestion, P1

#320 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/grpc/dotnet-grpc.md
Labels: Accepted, Linguistic Suggestion, P1

#315 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/blazor/hosting-models.md
Labels: Accepted, Linguistic Suggestion, P1

#319 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/visual-studio-publish-profiles.md
Labels: Accepted, Linguistic Suggestion, P1

#333 Fix table format broken
  aspnetcore/web-api/advanced/formatting.md
Labels: Accepted, Linguistic Suggestion, P1

#364 [LOC]Fixed inappropriate japanese "資産"→"アセット"
  aspnetcore/host-and-deploy/iis/index.md
Labels: Accepted, Linguistic Suggestion, P1
